repos:
  # Next hooks are Code Quality hooks.
  # These are OPTIONAL.

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: pretty-format-golang
        args:
          - --autofix